# Generated by Django 5.1.6 on 2025-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=3)),
                ('itemName', models.CharField(max_length=200)),
                ('itemType', models.CharField(max_length=10)),
                ('itemDescription', models.CharField(max_length=150)),
                ('itemPrice', models.FloatField(max_length=10)),
            ],
            options={
                'db_table': 'CarParts',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
