# Generated by Django 5.1.6 on 2025-02-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_carparts_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparts',
            name='itemImage',
            field=models.ImageField(blank=True, null=True, upload_to='car_parts/'),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='itemId',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='itemType',
            field=models.CharField(choices=[('Engine', 'Engine'), ('Brakes', 'Brakes'), ('Battery', 'Battery'), ('Transmission', 'Transmission'), ('Suspension', 'Suspension'), ('Exhaust', 'Exhaust'), ('Lights', 'Lights'), ('Tires', 'Tires')], max_length=20),
        ),
    ]
