# Generated by Django 5.1.6 on 2025-02-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_carparts_itemimage_alter_carparts_itemid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparts',
            name='itemId',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
